PROJECTNAME=	pkg_online_client

SCRIPTS=	pkg_online_find pkg_online_client
FILES=		pkg_online_client.env pkg_online_client.conf

FILESDIR=				${EGDIR}
FILESDIR_pkg_online_client.env=		${BINDIR}

INFILES=	pkg_online_client.env

.include <mkc.files.mk>
