#!/bin/sh

# Copyright (c) 2007-2010 Aleksey Cheusov <vle@gmx.net>
# All rights reserved.
#
# See LICENSE file
######################################################################

set -e

export PKG_DIGGER_BACKEND=${PKG_ONLINE_CLIENT-pkg_online_client}

pkg_digger "$@"
