#!/bin/sh

awk '
/^---/ {
    next
}

/^[^ ]/ && $1 ~ /^[Pp][Kk][Gg][Nn][Aa][Mm][Ee]:$/ {
    printf "_____\n\n%s\n", $2
    next
}

{
    print
}' "$@" |
dictfmt -c5 -q -s 'pkgsrc packages' --allchars \
   --without-headword --without-header -u 'http://www.pkgsrc.org' \
   --columns 0 pkgsrc
