fields_src='PKGPATH DEPENDS BUILD_DEPENDS CONFLICTS INDEX HOMEPAGE COMMENT LICENSE ONLYFOR NOTFOR MAINTAINER CATEGORIES PLIST DESCRIPTION'
fields_bin='PKGPATH DEPENDS CONFLICTS COMMENT BUILD_DATE CATEGORIES HOMEPAGE LICENSE OS_VERSION PKGTOOLS_VERSION PROVIDES REQUIRES DESCRIPTION'
