#!/bin/sh

set -e
. pipestatus

export LC_ALL=C

if test -n "$PKG_SUMMARY_TYPE"; then
    suff="-$PKG_SUMMARY_TYPE"
     msg=" $PKG_SUMMARY_TYPE"
fi

if test "$#" = 0; then
    echo 'usage: pkg_summary2field-index <comment|maintainer|...> [files...]' 1>&2
fi

field=$1
shift

summary2dict (){
awk -v field="$field" '
/^[^ ]/ && $1 ~ /^PKGNAME:$/ {
    pkgname = $2
    if (pkgname ~ /[0-9]$/){
	sub(/-[^-]*$/, "", pkgname)
    }

    next
}

field ~ /^(ONLY|NOT)FOR$/ && $1 == (field ":") && NF > 1 {
    if ($2 == "any"){
	next
    }

    $1 = ""
    printf "_____\n\n%s\n", substr($0, 2) "|%%|" pkgname
    next
}

$1 == (field ":") && NF > 1 {
    $1 = ""
    printf "_____\n\n%s\n", substr($0, 2) "|%%|" pkgname
    next
}

field == "PLIST" && $1 == (field ":"), NF == 0 {
    if (NF > 0 && $1 != (field ":")){
        sub(/^ +/, "")
        printf "_____\n\n%s\n", $0 "|%%|" pkgname
    }
    next
}

field == "DESCRIPTION" && $1 == (field ":"), NF == 0 {
    if ($0 ~ /^  /){
	descr = descr " " $0
    }

    if (NF == 0){
	printf "_____\n\n%s\n", substr(descr, 2) "|%%|" pkgname
	descr = ""
    }
    next
}
' "$@"
}

replace_8bit_symbs (){
    awk '{gsub(/[\200-\377]/, "<bad-symbol>"); print}'
}

runpipe0 \
    ./pkg_summary4view "$@" '|' \
    replace_8bit_symbs '|' \
    summary2dict '|' \
    dictfmt -c5 -q -s "pkgsrc packages: $field index" \
       --allchars --index-data-separator '|%%|' \
       --without-header --without-headword -u 'http://www.pkgsrc.org' \
       pkgsrc${suff}-index-"$field"
