#!/bin/sh

set -e

. pkg_online_env.sh
. pkg_online_server.sh
. pkg_online_summary_type.sh

export LC_ALL=C 

#
usage (){
    echo 'usage: pkg_online_info pkg1 [pkg2...]' 1>&2
}

if test $# -lt 1; then
    usage
    exit 1
fi

#
for i in "$@"; do
    dict -P - -h "$PKG_ONLINE_SERVER" -p "$PKG_ONLINE_PORT" \
	-d pkgsrc-"$PKG_SUMMARY_TYPE"-info "$i"
done
