#!/bin/sh

set -e
. pipestatus

export LC_ALL=C 

# temp dir
tmp_dir="/tmp/pkg_online.$$"
trap "rm -rf $tmp_dir" 0 1 2 3 15
mkdir -m 700 "$tmp_dir"

#
usage (){
    echo 'usage: pkg_online <bin|src> [search_images...]' 1>&2
}

#if test $# -lt 2; then
#    usage
#    exit 1
#fi

#
binsrc=$1
shift

#
res_fn=$tmp_dir/result
if ! pkg_online_get "$binsrc" "$@" > $res_fn; then
    exit 1
fi

#
comment_fn=$tmp_dir/comment
pkgname2comment (){
    dict -f -h "$PKG_ONLINE_SERVER" -p "$PKG_ONLINE_PORT" \
	-d pkgsrc-$binsrc-pkgname2comment "$@" |
    awk -F'\t' '
    NF == 4 {skip = 0}
    /^  / && !skip {print substr($0, 3); skip = 1}'
}

#
#pkgs="`cat $res_fn`"
#pkgname2comment $pkgs

#
#while read pkgname; do
#    comment=`pkgname2comment "$pkgname"`
#    printf '%25s: %s\n' "$pkgname" "$comment"
#done < "$res_fn"
cat "$res_fn"
