#!/bin/sh

. ./pkg_online_fields.sh

usage (){
    echo 'usage: pkg_online_mkconf <bin|src> <db_dir>' 1>&2
}

if test $# -ne 2; then
    usage
    exit 1
fi

binsrc=$1
db_dir=$2

shift
shift

database (){
cat <<EOF
database pkgsrc-$binsrc-index-$1 {
   index  "$db_dir/pkgsrc-$binsrc-index-$1.index"
   data   "$db_dir/pkgsrc-$binsrc-index-$1.dict"
}
EOF
}

# indices
cmd="echo \$fields_$binsrc"
fields=`eval $cmd`
for f in $fields; do
    database $f
done

# whole information about all packages
cat <<EOF
database pkgsrc-$binsrc-info {
   index  "$db_dir/pkgsrc-$binsrc-info.index"
   data   "$db_dir/pkgsrc-$binsrc-info.dict"
}
EOF

# pkg2comment database
cat <<EOF
database pkgsrc-$binsrc-pkgname2comment {
   index  "$db_dir/pkgsrc-$binsrc-pkgname2comment.index"
   data   "$db_dir/pkgsrc-$binsrc-pkgname2comment.dict"
}
EOF
