#!/bin/sh

set -e

. pkg_online_env.sh
. pkg_online_fields.sh
. pkg_online_summary_type.sh

eval fields="\$fields_$PKG_SUMMARY_TYPE"

# fields indices
for i in $fields
do
    printf "index for field %s" $i...
    pkg_summary2field-index $i "$@"
    printf "done\n"
done

# whole information
printf "%s" 'information about packages...'
pkg_summary2info "$@"
printf "done\n"

# pkgname2comment
printf 'pkgname2comment...'
pkg_summary2pkgname_to_comment "$@"
printf "done\n"
