#!/bin/sh

set -e
. pipestatus

if test -n "$PKG_SUMMARY_TYPE"; then
    suff="-$PKG_SUMMARY_TYPE"
     msg=" $PKG_SUMMARY_TYPE"
fi

summary2dict () {
awk '
/^---/ {
    next
}

/^[^ ]/ && $1 ~ /^[Pp][Kk][Gg][Nn][Aa][Mm][Ee]:$/ {
    basename = $2
    sub(/-[^-]*$/, "", basename)
    printf "_____\n\n%s\n%s\n", basename, $0
    next
}

{
    print
}'
}

runpipe0 \
    ./pkg_summary4view "$@" '|' \
    summary2dict '|' \
    dictfmt -c5 -q -s "Information about pkgsrc${msg} packages" \
       --allchars --without-headword --without-header \
       -u 'http://www.pkgsrc.org' \
       --columns 0 pkgsrc${suff}-info
