#!/bin/sh

# Copyright (c) 2007-2008 Aleksey Cheusov <vle@gmx.net>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -e

. pkg_online_client.env
. pipestatus

export LC_ALL=C

# temp dir
tmp_dir="/tmp/pkg_online.$$"
trap "rm -rf $tmp_dir" 0 1 2 3 15
mkdir -m 700 "$tmp_dir"

#
res_fn=$tmp_dir/result
if ! pkg_online_find "$@" > $res_fn; then
    exit 1
fi

#
comment_fn=$tmp_dir/comment
pkgname2comment (){
    dict -f -h "$PKG_ONLINE_SERVER" -p "$PKG_ONLINE_PORT" \
	-d pkgsrc-${PKG_SUMMARY_TYPE}-pkgname2comment "$@" #|
#    awk -F'\t' '
#    NF == 4 {skip = 0}
#    /^  / && !skip {print substr($0, 3); skip = 1}'
}

#
#pkgs="`cat $res_fn`"
#pkgs="``"
pkgname2comment `cat $res_fn` |
awk -v res_fn="$res_fn" -F'\t' '
NF == 4 {
    getline comment
    getline pkgname < res_fn
    printf "%20s - %s\n", pkgname, comment
    fflush()
}'

#
#while read pkgname; do
#    comment=`pkgname2comment "$pkgname"`
#    printf '%25s: %s\n' "$pkgname" "$comment"
#done < "$res_fn"
#cat "$res_fn"
