#!/bin/sh

set -e

. pipestatus
. pkg_online_summary_type.sh

export LC_ALL=C

suff="-$PKG_SUMMARY_TYPE"
msg=" $PKG_SUMMARY_TYPE"

summary2dict () {
awk '
/^PKGNAME=/ {
    pkgname = $1
    sub(/^PKGNAME=/, "", pkgname)
    if (pkgname ~ /[0-9]$/){
	sub(/-[^-]*$/, "", pkgname)
    }

    next
}

/^COMMENT=/ {
    sub(/^COMMENT=/, "")
    printf "_____\n\n%s\n%s\n", pkgname, $0
}
' "$@"
}

runpipe0 \
    summary2dict "$@" '|' \
    dictfmt -c5 -q -s "pkgsrc packages: pkgname2comment database" \
        --allchars --index-data-separator '|%%|' \
        --without-header --without-headword -u 'http://www.pkgsrc.org' \
        pkgsrc${suff}-pkgname2comment
