#!/bin/sh

set -e

. pipestatus
. pkg_online_summary_type.sh

export LC_ALL=C

suff="-$PKG_SUMMARY_TYPE"
msg=" $PKG_SUMMARY_TYPE"

summary2dict () {
awk '
/^---/ {
    next
}

/^[^ ]/ && $1 ~ /^[Pp][Kk][Gg][Nn][Aa][Mm][Ee]:$/ {
    basename = $2
    if (basename ~ /[0-9]$/){
	sub(/-[^-]*$/, "", basename)
    }
    printf "_____\n\n%s\n%s\n", basename, $0
    next
}

{
    print
}'
}

runpipe0 \
    pkg_summary4view "$@" '|' \
    summary2dict '|' \
    dictfmt -c5 -q -s "Information about pkgsrc${msg} packages" \
       --allchars --without-headword --without-header \
       -u 'http://www.pkgsrc.org' \
       --columns 0 pkgsrc${suff}-info
