#!/bin/sh

set -e

. pkg_online_env.sh
. pkg_online_server.sh
. pkg_online_summary_type.sh
. pipestatus

export LC_ALL=C

# temp dir
tmp_dir="/tmp/pkg_online.$$"
trap "rm -rf $tmp_dir" 0 1 2 3 15
mkdir -m 700 "$tmp_dir"

#
res_fn=$tmp_dir/result
if ! pkg_online_find "$@" > $res_fn; then
    exit 1
fi

#
comment_fn=$tmp_dir/comment
pkgname2comment (){
    dict -f -h "$PKG_ONLINE_SERVER" -p "$PKG_ONLINE_PORT" \
	-d pkgsrc-${PKG_SUMMARY_TYPE}-pkgname2comment "$@" #|
#    awk -F'\t' '
#    NF == 4 {skip = 0}
#    /^  / && !skip {print substr($0, 3); skip = 1}'
}

#
#pkgs="`cat $res_fn`"
#pkgs="``"
pkgname2comment `cat $res_fn` |
awk -v res_fn="$res_fn" -F'\t' '
NF == 4 {
    getline comment
    getline pkgname < res_fn
    printf "%20s - %s\n", pkgname, comment
    fflush()
}'

#
#while read pkgname; do
#    comment=`pkgname2comment "$pkgname"`
#    printf '%25s: %s\n' "$pkgname" "$comment"
#done < "$res_fn"
#cat "$res_fn"
