#!/bin/sh


set -e

. pkg_online_env.sh
. pkg_online_fields.sh
. pkg_online_summary_type.sh

usage (){
    echo 'usage: pkg_online_mkconf <db_dir>' 1>&2
}

if test $# -ne 1; then
    usage
    exit 1
fi

db_dir=$1
shift

index_database (){
cat <<EOF
# index database for field $1
database pkgsrc-$PKG_SUMMARY_TYPE-index-$1 {
   index  "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-index-$1.index"
   data   "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-index-$1.dict"
}
EOF
}

# whole information about all packages
cat <<EOF
# MAIN database
database pkgsrc-$PKG_SUMMARY_TYPE-info {
   index  "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-info.index"
   data   "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-info.dict"
}
EOF

# pkg2comment database
cat <<EOF
# PKGNAME2COMMENT database
database pkgsrc-$PKG_SUMMARY_TYPE-pkgname2comment {
   index  "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-pkgname2comment.index"
   data   "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-pkgname2comment.dict"
}
EOF

# indices
cmd="echo \$fields_$PKG_SUMMARY_TYPE"
fields=`eval $cmd`
for f in $fields; do
    index_database $f
done
