#!/bin/sh

set -e

#
usage (){
    echo 'usage: pkg_summary2all <bin|src> <files...>'
}

if test $# -gt 2 || test _$1 '!=' _bin -a _$1 '!=' _src
then
    usage
    exit 1
fi

#
binsrc=$1
shift;

if test _$binsrc = _bin
then
    fields='PKGPATH DEPENDS CONFLICTS COMMENT BUILD_DATE CATEGORIES HOMEPAGE LICENSE OS_VERSION PKGTOOLS_VERSION PROVIDES REQUIRES DESCRIPTION'
else
    fields='PKGPATH DEPENDS BUILD_DEPENDS CONFLICTS INDEX HOMEPAGE COMMENT LICENSE ONLYFOR NOTFOR MAINTAINER CATEGORIES PLIST DESCRIPTION'
fi

export PKG_SUMMARY_TYPE=$binsrc

for i in $fields
do
    printf "index for field %s" $i...
    ./pkg_summary2field-index $i "$@"
    printf "done\n"
done

printf "%s" 'information about packages...'
echo ./pkg_summary2dict "$@"
./pkg_summary2dict "$@"
printf "done\n"
