#!/bin/sh

# Copyright (c) 2007-2008 Aleksey Cheusov <vle@gmx.net>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -e

. pkg_online_server.env
. pipestatus

export LC_ALL=C

suff="-$PKG_SUMMARY_TYPE"
msg=" $PKG_SUMMARY_TYPE"

summary2dict () {
awk '
/^PKGNAME=/ {
    pkgname = $1
    sub(/^PKGNAME=/, "", pkgname)
    if (pkgname ~ /[0-9]$/){
	sub(/-[^-]*$/, "", pkgname)
    }

    next
}

/^COMMENT=/ {
    sub(/^COMMENT=/, "")
    comment = $0
}

/^PKGPATH=/ {
    sub(/^PKGPATH=/, "")
    pkgpath = $0
}

NF == 0 {
    printf "_____\n\n%s\n%10s - %s\n", pkgname, pkgpath, comment
}
' "$@"
}

runpipe0 \
    summary2dict "$@" '|' \
    dictfmt -c5 -q -s "pkgsrc packages: pkgname2onelineinfo database" \
        --allchars --index-data-separator '|%%|' \
        --without-header --without-headword -u 'http://www.pkgsrc.org' \
        pkgsrc${suff}-pkgname2onelineinfo --columns 0
