#!/bin/sh

if test -n "$PKG_SUMMARY_TYPE"; then
    suff="-$PKG_SUMMARY_TYPE"
     msg=" $PKG_SUMMARY_TYPE"
fi

awk '
/^---/ {
    next
}

/^[^ ]/ && $1 ~ /^[Pp][Kk][Gg][Nn][Aa][Mm][Ee]:$/ {
    printf "_____\n\n%s\n", $2
    next
}

{
    print
}' "$@" |
dictfmt -c5 -q -s "Information about pkgsrc${msg} packages" --allchars \
   --without-headword --without-header -u 'http://www.pkgsrc.org' \
   --columns 0 pkgsrc${suff}
