#!/bin/sh

set -e

. pipestatus
. pkg_online_summary_type.sh

export LC_ALL=C

suff="-$PKG_SUMMARY_TYPE"
msg=" $PKG_SUMMARY_TYPE"

if test "$#" = 0; then
    echo 'usage: pkg_summary2field-index <comment|maintainer|...> [files...]' 1>&2
    exit 1
fi

field=$1
shift

summary2dict (){
awk -v field="$field" -F= '
function print_description (){
    printf "_____\n\n%s\n", substr(descr, 2) "|%%|" pkgname
    descr = ""
    last  = ""
}

$1 != last && last == "DESCRIPTION" {
    print_description()
}

$1 == "PKGNAME" {
    last    = $1
    pkgname = $2

    sub(/^[^=]*=/, "")

    if (pkgname ~ /[0-9]$/){
	sub(/-[^-]*$/, "", pkgname)
    }

    next
}

field ~ /^(ONLY|NOT)FOR$/ && $1 == field && NF > 1 {
    last = $1

    if ($2 == "any"){
	next
    }

    sub(/^[^=]*=/, "")

    printf "_____\n\n%s\n", $0 "|%%|" pkgname
    next
}

field == "DESCRIPTION" && $1 == field {
    last = $1

    sub(/^[^=]*=/, "")

    descr = descr " " $0

    next
}

$1 == field && NF > 1 {
    last = $1

    sub(/^[^=]*=/, "")

    printf "_____\n\n%s\n", $0 "|%%|" pkgname
    next
}

END {
    if (last == "DESCRIPTION") {
        print_description()
    }
}

' "$@"
}

replace_8bit_symbs (){
    tr -d '\200-\377'
}

runpipe0 \
    cat "$@" '|' \
    replace_8bit_symbs '|' \
    summary2dict '|' \
    dictfmt -c5 -q -s "$field index" \
       --allchars --index-data-separator '|%%|' \
       --without-header --without-headword -u 'http://www.pkgsrc.org' \
       pkgsrc${suff}-index-"$field"
