#!/bin/sh -e

############################################################
if test -z "$PKGSRC"; then
    PKGSRC=/usr/pkgsrc
fi

if test -z "$BMAKE"; then
    BMAKE=make
fi

############################################################
cd $PKGSRC

tmpfn=/tmp/pkgdirs2info.$$
trap 'rm -f $tmpfn' 0 1 2 15

############################################################
capitalize (){
    echo $1 | awk '{print toupper(substr($0, 1, 1)) substr($0, 2)}'
}

summary_data2info (){
    awk '
    $1 == "prefix" {
	next
    }

    function normalize (w){
	return toupper(w)
#	return toupper(substr(w, 1, 1)) substr(w, 2)
    }

    $1 == "descr" {
	print "\n" normalize("descr:")
	fn = $3
	while (0 < ret = (getline < fn)){
	    print "  " $0
	}
	if (ret < 0){
	    printf "reading from `" fn "` failed\n" > "/dev/stderr"
	    exit 1
	}
	print ""
	next
    }

    {
	$2 = ""
	$1 = (normalize($1) ":")
	if ($3 != ""){
	    while(length($1) < 15){
		$1 = ($1 " ")
	    }
	}

	print $0
    }'
}

generate_info (){
    echo '------------------------------'

    # general information
    ( cd $1; ${BMAKE} print-summary-data; ) > "$tmpfn";
    pkgname=`awk '$1 == "index" {sub(/-[^-]*$/, "", $3); print $3}' "$tmpfn"`
    pkgdir=`awk '$1 == "index" {print $2}' "$tmpfn"`
    echo "PKGNAME:         $pkgname"
    echo "PKGDIR:          $pkgdir"
    cat "$tmpfn" | summary_data2info

    # plist
    capitalize "PLIST:"
    plist_fn=$1/PLIST
    if test -f $plist_fn; then
	awk '/^[^@]/ {print "  " $0}' $plist_fn
    else
	echo ''
    fi
}

############################################################
for i; do
    generate_info "$i"
    echo ''
done
