#!/bin/sh -e

############################################################
if test -z "$PKGSRC"; then
    PKGSRC=/usr/pkgsrc
fi

if test -z "$BMAKE"; then
    BMAKE=make
fi

############################################################
cd $PKGSRC

############################################################
capitalize (){
    echo $1 | awk '{print toupper(substr($0, 1, 1)) substr($0, 2)}'
}

summary_data2info (){
    awk '
    $1 == "prefix" {
	next
    }

    function normalize (w){
	return toupper(w)
#	return toupper(substr(w, 1, 1)) substr(w, 2)
    }

    $1 == "descr" {
	print "\n" normalize("descr:")
	fn = $3
	while (0 < ret = (getline < fn)){
	    print "  " $0
	}
	if (ret < 0){
	    printf "reading from `" fn "` failed\n" > "/dev/stderr"
	    exit 1
	}
	print ""
	next
    }

    {
	$2 = ""
	$1 = (normalize($1) ":")
	if ($3 != ""){
	    while(length($1) < 15){
		$1 = ($1 " ")
	    }
	}

	print $0
    }'
}

generate_info (){
    echo '------------------------------'
    echo "PKGDIR:          $1"

    # general information
    ( cd $1; ${BMAKE} print-summary-data; ) | summary_data2info

    # plist
    capitalize "PLIST:"
    awk '/^[^@]/ {print "  " $0}' $1/PLIST
}

############################################################
for i; do
    generate_info "$i"
    echo ''
done
