DOCDIR?=	${PREFIX}/share/doc/pkg_online

##################################################

PROJECTNAME=	pkg_online_doc

FILES=		README NEWS TODO 
FILESDIR?=	${DOCDIR}

##################################################

.include <mkc.files.mk>
