#!/bin/sh

# Copyright (c) 2007-2008 Aleksey Cheusov <cheusov@NetBSD.org>
# All rights reserved.
#
# See LICENSE file
######################################################################

set -e

. pkg_online_server.env
. pipestatus

export LC_ALL=C

suff="-$PKG_SUMMARY_TYPE"
msg=" $PKG_SUMMARY_TYPE"

summary2dict () {
awk '
/^PKGNAME=/ {
    pkgname = pkgbase = substr($0, 9)
    sub(/-[^-]*$/, "", pkgbase)

    next
}

/^COMMENT=/ {
    sub(/^COMMENT=/, "")
    comment = $0
}

/^PKGPATH=/ {
    sub(/^PKGPATH=/, "")
    pkgpath = $0
}

NF == 0 {
    printf "_____\n\n%s,%s\nPKGNAME=%s\nPKGPATH=%s\nCOMMENT=%s\n\n", pkgpath, pkgbase, pkgname, pkgpath, comment
    pkgname = pkgbase = pkgpath = comment = ""
}
' "$@"
}

runpipe0 \
    summary2dict "$@" '|' \
    dictfmt -c5 -q -s "pkgsrc packages: onelineinfo database" \
        --allchars --index-data-separator '|%%|' \
        --without-header --without-headword -u 'http://www.pkgsrc.org' \
        pkgsrc${suff}-onelineinfo --columns 0
