#!/bin/sh

# Copyright (c) 2007-2008 Aleksey Cheusov <cheusov@NetBSD.org>
# All rights reserved.
#
# See LICENSE file
######################################################################

set -e

. pkg_online_server.env
. pipestatus

export LC_ALL=C

suff="-$PKG_SUMMARY_TYPE"
msg=" $PKG_SUMMARY_TYPE"

runpipe0 \
    pkg_summary2dict "$@" '|' \
    dictfmt -c5 -q -s "Information about pkgsrc${msg} packages" \
       --allchars --without-headword --without-header \
       -u 'http://www.pkgsrc.org' \
       --columns 0 pkgsrc${suff}-info
