#!/usr/bin/awk -f

# Copyright (c) 2007-2008 Aleksey Cheusov <cheusov@NetBSD.org>
# All rights reserved.
#
# See LICENSE file
######################################################################

NF == 0 {
	printf "_____\n\n%s,%s\n", pkgpath, pkgbase
	for (i=1; i <= count; ++i){
		print summary [i]
	}
	print ""
	pkgbase = pkgpath = ""
	count = 0
	next
}

{
	if ($0 ~ /^PKGNAME=/){
		pkgbase = substr($0, 9)
		sub(/-[^-]*$/, "", pkgbase)
	}
	if ($0 ~ /^PKGPATH=/){
		pkgpath = substr($0, 9)
	}
	summary [++count] = $0
}
