#!/bin/sh

# Copyright (c) 2007-2008 Aleksey Cheusov <cheusov@NetBSD.org>
# All rights reserved.
#
# See LICENSE file
######################################################################

set -e

. pkg_online_server.env

eval fields="\$fields_$PKG_SUMMARY_TYPE"

# fields indices
for i in $fields
do
    printf "index for field %s" $i...
    pkg_summary2field-index $i "$@"
    printf "done\n"
done

# whole information
printf "%s" 'information about packages...'
pkg_summary2info "$@"
printf "done\n"

# onelineinfo
printf 'onelineinfo...'
pkg_summary2onelineinfo "$@"
printf "done\n"

# shortinfo
printf 'shortinfo...'
pkg_summary2shortinfo "$@"
printf "done\n"
