#!/bin/sh

# Copyright (c) 2007-2008 Aleksey Cheusov <cheusov@NetBSD.org>
# All rights reserved.
#
# See LICENSE file
######################################################################

set -e

. pkg_online_server.env

usage (){
    echo 'usage: pkg_online_mkconf <db_dir>' 1>&2
}

if test $# -ne 1; then
    usage
    exit 1
fi

db_dir=$1
shift

index_database (){
cat <<EOF
# index database for field $1
database pkgsrc-$PKG_SUMMARY_TYPE-index-$1 {
   index  "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-index-$1.index"
   data   "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-index-$1.dict"
}
EOF
}

# whole information about all packages
cat <<EOF
# INFO database
database pkgsrc-$PKG_SUMMARY_TYPE-info {
   index  "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-info.index"
   data   "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-info.dict"
}
EOF

# onelineinfo database
cat <<EOF
# ONELINEINFO database
database pkgsrc-$PKG_SUMMARY_TYPE-onelineinfo {
   index  "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-onelineinfo.index"
   data   "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-onelineinfo.dict"
}
EOF

# shortinfo database
cat <<EOF
# SHORTINFO database
database pkgsrc-$PKG_SUMMARY_TYPE-shortinfo {
   index  "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-shortinfo.index"
   data   "$db_dir/pkgsrc-$PKG_SUMMARY_TYPE-shortinfo.dict"
}
EOF

# indices
cmd="echo \$fields_$PKG_SUMMARY_TYPE"
fields=`eval $cmd`
for f in $fields; do
    index_database $f
done
